apiVersion: v1
kind: Secret
metadata:
  name: spots-secrets
  namespace: hazard-spots
  labels:
    project: hazard-spots
    component: security
type: Opaque
stringData:
  POSTGRES_USER: spotsadmin
  POSTGRES_PASSWORD: S3cureSpot$123
  API_TOKEN: hazard-api-token
