apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: app
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/part-of: todos
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: todo-api
  ports:
    - name: http
      port: 80
      targetPort: http
