apiVersion: gateway.networking.k8s.io/v1beta1
kind: GatewayClass
metadata:
  name: azure-lb
  labels:
    project: hazard-spots
spec:
  controllerName: azure.com/aks-gateway-controller
  description: Standard load balancer backed GatewayClass for AKS
