apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ripley-hazard
  namespace: hazard-spots
  labels:
    app: ripley-hazard
    component: routing
spec:
  parentRefs:
    - name: ripley-hazard-gateway
      sectionName: http
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ripley-hazard
          port: 80
          weight: 1
