apiVersion: apps/v1
kind: Deployment
metadata:
  name: ripley-hazard
  namespace: hazard-spots
  labels:
    app: ripley-hazard
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ripley-hazard
  template:
    metadata:
      labels:
        app: ripley-hazard
        component: frontend
    spec:
      containers:
        - name: ripley-hazard
          image: nicholasjackson/fake-service:v0.26.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LISTEN_ADDR
              valueFrom:
                configMapKeyRef:
                  name: ripley-hazard-config
                  key: LISTEN_ADDR
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: ripley-hazard-config
                  key: MESSAGE
            - name: NAME
              value: "ripley-hazard"
            - name: UPSTREAM_URIS
              valueFrom:
                configMapKeyRef:
                  name: ripley-hazard-config
                  key: UPSTREAM_URIS
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: spots-secrets
                  key: API_TOKEN
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
