apiVersion: v1
kind: Service
metadata:
  name: spots-api
  namespace: hazard-spots
  labels:
    app: spots-api
    component: backend
spec:
  selector:
    app: spots-api
  ports:
    - port: 8080
      targetPort: http
      name: http
  type: ClusterIP
