apiVersion: v1
kind: Service
metadata:
  name: spots-db
  namespace: hazard-spots
  labels:
    app: spots-db
    role: database
spec:
  clusterIP: None
  selector:
    app: spots-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
