apiVersion: v1
kind: Service
metadata:
  name: ripley-hazard
  namespace: hazard-spots
  labels:
    app: ripley-hazard
    component: frontend
spec:
  selector:
    app: ripley-hazard
  ports:
    - port: 80
      targetPort: http
      name: http
  type: LoadBalancer
